/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gerenciadordepopulacoes.view;

import com.mycompany.gerenciadordepopulacoes.database.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonat
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtUsuario = new javax.swing.JTextField();
        PsfSenha = new javax.swing.JPasswordField();
        BtnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtUsuario.setBorder(null);
        TxtUsuario.addActionListener(this::TxtUsuarioActionPerformed);
        jPanel1.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 160, 20));

        PsfSenha.setBorder(null);
        PsfSenha.addActionListener(this::PsfSenhaActionPerformed);
        jPanel1.add(PsfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 160, 20));

        BtnLogin.setBackground(new java.awt.Color(153, 0, 51));
        BtnLogin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("Login");
        BtnLogin.setBorder(null);
        BtnLogin.addActionListener(this::BtnLoginActionPerformed);
        jPanel1.add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 110, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Iniciar Sessão");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 163, -1));

        jLabel2.setText("Nome");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 37, -1));

        jLabel3.setText("Senha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 37, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2148996474.jpg"))); // NOI18N
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 260, 390));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 160, -1));

        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
       tentarLogin();
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void PsfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PsfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PsfSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JPasswordField PsfSenha;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables


private void tentarLogin() {
    String usuario = TxtUsuario.getText().trim();
    String senha = new String(PsfSenha.getPassword()); 
    
    String senhaHashSimulada = senha; 

    String sql = "SELECT nivel_acesso, id_empresa, ativo FROM usuarios WHERE nome_usuario = ? AND senha_hash = ?";

    if (usuario.isEmpty() || senha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos.", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try (Connection conn = new Conexao().getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setString(1, usuario);
        stmt.setString(2, senhaHashSimulada); // JONATHAN: FUNCIONOU USANDO ESSA LINHA ENTÃO NÃO MUDA ELA ATÉ EU MESMO MUDAR
        
        try (ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                
                if (!rs.getBoolean("ativo")) {
                    JOptionPane.showMessageDialog(this, "Usuário inativo.", "Acesso Negado", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                String nivel = rs.getString("nivel_acesso");
                int idEmpresa = rs.getInt("id_empresa");

                Sessao.iniciarSessao(usuario, nivel, idEmpresa);

                JOptionPane.showMessageDialog(this, "Login efetuado! Nível: " + nivel);
                
                Principal principal = new Principal();
                principal.setVisible(true);
                this.dispose(); 

            } else {
                JOptionPane.showMessageDialog(this, "Usuário ou senha inválidos.", "Erro de Login", JOptionPane.ERROR_MESSAGE);
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro de conexão ou consulta ao banco: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

public class Sessao {
    
    private static String usuarioLogado;
    private static String nivelAcesso; 
    private static int idEmpresa;

   
    public static void iniciarSessao(String usuario, String nivel, int idEmp) {
        Sessao.usuarioLogado = usuario;
        Sessao.nivelAcesso = nivel;
        Sessao.idEmpresa = idEmp;
        System.out.println("Sessão iniciada para: " + usuario + " (Nível: " + nivel + ")");
    }


    public static void encerrarSessao() {
        Sessao.usuarioLogado = null;
        Sessao.nivelAcesso = null;
        Sessao.idEmpresa = 0;
        System.out.println("Sessão encerrada.");
    }

    public static String getUsuarioLogado() {
        return usuarioLogado;
    }

 
    public static String getNivelAcesso() {
        return nivelAcesso;
    }

    public static int getIdEmpresa() {
        return idEmpresa;
    }
}


}
