/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gerenciadordepopulacoes.view;

import com.mycompany.gerenciadordepopulacoes.dao.AuxDAO;
import com.mycompany.gerenciadordepopulacoes.dao.GrupoPopulacionalDAO;
import com.mycompany.gerenciadordepopulacoes.dao.UnidadeGeograficaDAO;
import com.mycompany.gerenciadordepopulacoes.database.Conexao;
import com.mycompany.gerenciadordepopulacoes.util.RelatorioUtil;
import com.mycompany.gerenciadordepopulacoes.view.Login.Sessao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;


/**
 *
 * @author Jonat
 */
public class Principal extends javax.swing.JFrame {
    
    private int idGrupoEmEdicao = 0; 
    private int idPaisEmEdicao = 0;
    private int idEstadoEmEdicao = 0;
    private int idUsuarioEmEdicao = 0; 
    // ...
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    private final GrupoPopulacionalDAO grupoDAO = new GrupoPopulacionalDAO();
    private final UnidadeGeograficaDAO unidadeDAO = new UnidadeGeograficaDAO();
    
    public Principal() {
        initComponents();
        
        configurarPermissoes();
        
        carregarUnidadesNaArvore();
        adicionarListenerNaArvore();
        
        carregarCbxEstados(); 
        carregarTabelaEdicao(); 
        adicionarListenerTabelaEdicao();
        
        carregarCbxPais();        
        carregarTabelaPaises();   
        carregarTabelaEstados();
        
        adicionarListenerTabelaPaises();
        adicionarListenerTabelaEstados();
        carregarCmbmpresas();
        carregarCmbNiveisAcesso();
        carregarTabelaUsuarios();
        adicionarListenerTabelaUsuarios();
        atualizar();

        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            Sessao.encerrarSessao();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        TxtTamanho = new javax.swing.JTextField();
        TxtNacionalidade = new javax.swing.JTextField();
        TxtTipo = new javax.swing.JTextField();
        TxtReligiao = new javax.swing.JTextField();
        BtnExcluir = new javax.swing.JButton();
        BtnLimpar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        CbxEstado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblGruposEdicao = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        TxtNomePais = new javax.swing.JTextField();
        BtnSalvarPais = new javax.swing.JButton();
        BtnExcluirPais = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TblPaises = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        TxtNomeEstado = new javax.swing.JTextField();
        BtnSalvarEstado = new javax.swing.JButton();
        CbxPais = new javax.swing.JComboBox<>();
        BtnExcluirEstado = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TblEstados = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        TxtNomeUsuario = new javax.swing.JTextField();
        PsfSenhaCadastro = new javax.swing.JPasswordField();
        TxtEmail = new javax.swing.JTextField();
        CmbEmpresa = new javax.swing.JComboBox<>();
        CmbNivelAcesso = new javax.swing.JComboBox<>();
        BtnSalvarUsuario = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TblUsuarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtrUnidades = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tblnformacoes = new javax.swing.JTable();

        jScrollPane4.setViewportView(jEditorPane1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setOpaque(true);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        TxtTipo.addActionListener(this::TxtTipoActionPerformed);

        TxtReligiao.addActionListener(this::TxtReligiaoActionPerformed);

        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(this::BtnExcluirActionPerformed);

        BtnLimpar.setText("Limpar");
        BtnLimpar.addActionListener(this::BtnLimparActionPerformed);

        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(this::BtnSalvarActionPerformed);

        jLabel1.setText("Tamanho");

        jLabel2.setText("Tipo");

        jLabel3.setText("Nacionalidade");

        jLabel4.setText("Religião");

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblGruposEdicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TblGruposEdicao);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 740, 250));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(TxtTamanho)
                    .addComponent(BtnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnLimpar)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TxtNacionalidade)
                        .addComponent(TxtReligiao, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addComponent(BtnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(CbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(CbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtReligiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnLimpar)
                    .addComponent(BtnSalvar))
                .addGap(12, 12, 12)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/notepad.png")), jPanel2); // NOI18N

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));

        BtnSalvarPais.setText("Salvar");
        BtnSalvarPais.addActionListener(this::BtnSalvarPaisActionPerformed);

        BtnExcluirPais.setText("Excluir");
        BtnExcluirPais.addActionListener(this::BtnExcluirPaisActionPerformed);

        jLabel5.setText("Nome");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(BtnExcluirPais)
                        .addGap(150, 150, 150)
                        .addComponent(BtnSalvarPais))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNomePais, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(49, 49, 49)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalvarPais)
                    .addComponent(BtnExcluirPais))
                .addGap(36, 36, 36))
        );

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblPaises.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TblPaises);

        jPanel10.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 740, 240));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/countries.png")), jPanel8); // NOI18N

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));

        BtnSalvarEstado.setText("Salvar");
        BtnSalvarEstado.addActionListener(this::BtnSalvarEstadoActionPerformed);

        CbxPais.addActionListener(this::CbxPaisActionPerformed);

        BtnExcluirEstado.setText("Excluir");
        BtnExcluirEstado.addActionListener(this::BtnExcluirEstadoActionPerformed);

        jLabel6.setText("Nome");

        TblEstados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(TblEstados);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnExcluirEstado)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TxtNomeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(BtnSalvarEstado))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(CbxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(47, 47, 47)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalvarEstado)
                    .addComponent(BtnExcluirEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/table.png")), jPanel11); // NOI18N

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(TxtNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 120, -1));

        PsfSenhaCadastro.addActionListener(this::PsfSenhaCadastroActionPerformed);
        jPanel15.add(PsfSenhaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 120, -1));

        TxtEmail.addActionListener(this::TxtEmailActionPerformed);
        jPanel15.add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 120, -1));

        jPanel15.add(CmbEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 130, -1));

        CmbNivelAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel15.add(CmbNivelAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 130, -1));

        BtnSalvarUsuario.setText("Cadastrar");
        BtnSalvarUsuario.addActionListener(this::BtnSalvarUsuarioActionPerformed);
        jPanel15.add(BtnSalvarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jLabel7.setText("Nome");
        jPanel15.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 50, -1));

        jLabel8.setText("Email");
        jPanel15.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel9.setText("Senha");
        jPanel15.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 50, -1));

        TblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(TblUsuarios);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane7)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/user.png")), jPanel14); // NOI18N

        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        JtrUnidades.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JtrUnidades.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(JtrUnidades);

        jButton1.setText("Imprimir");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        Tblnformacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tamanho", "Tipo", "Nacionalidade", "Religiao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tblnformacoes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(52, 52, 52))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(138, 138, 138))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 390));

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/binoculars.png")), jPanel1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        salvarGrupo();
        atualizar();
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        limparCampos();
        atualizar();
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        excluirGrupo();
        atualizar();
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void CbxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxPaisActionPerformed
    }//GEN-LAST:event_CbxPaisActionPerformed

    private void BtnSalvarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarEstadoActionPerformed
        salvarEstado();
        atualizar();
    }//GEN-LAST:event_BtnSalvarEstadoActionPerformed

    private void BtnSalvarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarPaisActionPerformed
        salvarPais();
        atualizar();
    }//GEN-LAST:event_BtnSalvarPaisActionPerformed

    private void BtnExcluirEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirEstadoActionPerformed
        excluirEstado();
    }//GEN-LAST:event_BtnExcluirEstadoActionPerformed

    private void BtnExcluirPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirPaisActionPerformed
        excluirPais();
    }//GEN-LAST:event_BtnExcluirPaisActionPerformed

    private void TxtReligiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtReligiaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtReligiaoActionPerformed

    private void TxtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gerarRelatorio("Relatorio_GerenciadorPop");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarUsuarioActionPerformed
        salvarUsuario();
        atualizar();

    }//GEN-LAST:event_BtnSalvarUsuarioActionPerformed

    private void TxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailActionPerformed

    private void PsfSenhaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PsfSenhaCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PsfSenhaCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnExcluirEstado;
    private javax.swing.JButton BtnExcluirPais;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JButton BtnSalvarEstado;
    private javax.swing.JButton BtnSalvarPais;
    private javax.swing.JButton BtnSalvarUsuario;
    private javax.swing.JComboBox<AuxDAO> CbxEstado;
    private javax.swing.JComboBox<AuxDAO> CbxPais;
    private javax.swing.JComboBox<AuxDAO> CmbEmpresa;
    private javax.swing.JComboBox<String> CmbNivelAcesso;
    private javax.swing.JTree JtrUnidades;
    private javax.swing.JPasswordField PsfSenhaCadastro;
    private javax.swing.JTable TblEstados;
    private javax.swing.JTable TblGruposEdicao;
    private javax.swing.JTable TblPaises;
    private javax.swing.JTable TblUsuarios;
    private javax.swing.JTable Tblnformacoes;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtNacionalidade;
    private javax.swing.JTextField TxtNomeEstado;
    private javax.swing.JTextField TxtNomePais;
    private javax.swing.JTextField TxtNomeUsuario;
    private javax.swing.JTextField TxtReligiao;
    private javax.swing.JTextField TxtTamanho;
    private javax.swing.JTextField TxtTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

private void carregarTabelaGrupos(int idEstado) {
        String[] colunas = {"Tamanho", "Tipo", "Nacionalidade", "Religião"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);
        
        try {
            List<Object[]> grupos = grupoDAO.buscarGruposPorEstado(idEstado); 

            for (Object[] linha : grupos) {
                modelo.addRow(linha);
            }
            
            Tblnformacoes.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar Grupos Populacionais: " + e.getMessage());
            Tblnformacoes.setModel(new DefaultTableModel(colunas, 0));
        }
    }

    private void carregarTabelaEdicao() {
        String[] colunas = {"ID", "Tamanho", "Tipo", "Nacionalidade", "Religiao", "Estado"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0); 
        
        try {
            List<Object[]> grupos = grupoDAO.listarGruposComEstados();
            
            for (Object[] linha : grupos) {
                modelo.addRow(linha);
            }
            TblGruposEdicao.setModel(modelo);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar grupos para edicao: " + e.getMessage());
        }
    }
    
    private void salvarGrupo() {
        boolean modoEdicao = (idGrupoEmEdicao > 0);
        
        AuxDAO estadoSelecionado = (AuxDAO) CbxEstado.getSelectedItem();
        if (estadoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um Estado.");
            return;
        }
        int idEstado = estadoSelecionado.getId();
        
        int tamanho;
        try {
            tamanho = Integer.parseInt(TxtTamanho.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O campo Tamanho deve ser um número inteiro válido.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String tipo = TxtTipo.getText();
        String nacionalidade = TxtNacionalidade.getText();
        String religiao = TxtReligiao.getText();
        
        try {
            grupoDAO.salvarGrupo(idGrupoEmEdicao, tamanho, tipo, nacionalidade, religiao, idEstado);

            JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
            
            carregarTabelaEdicao(); 
            limparCampos();
            carregarUnidadesNaArvore(); 
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar/editar: " + e.getMessage());
        }
    }
    
    private void excluirGrupo() {
        if (idGrupoEmEdicao == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um Grupo Populacional na tabela para excluir.", "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmacao = JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja excluir o Grupo ID: " + idGrupoEmEdicao + "?", 
            "Confirmar Exclusao", 
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                // CHAMA O DAO
                int linhasAfetadas = grupoDAO.excluirGrupo(idGrupoEmEdicao);

                if (linhasAfetadas > 0) {
                    JOptionPane.showMessageDialog(this, "Grupo Populacional excluído com sucesso!");
                    
                    limparCampos(); 
                    carregarTabelaEdicao();
                    carregarUnidadesNaArvore(); 
                } else {
                    JOptionPane.showMessageDialog(this, "Nenhum grupo encontrado com o ID: " + idGrupoEmEdicao);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o registro -> " + e.getMessage(), "Erro SQL", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    

    private void carregarUnidadesNaArvore() {
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Unidades Geográficas");
        
        DefaultMutableTreeNode noPaisAtual = null;
        int idPaisAnterior = -1;

        try {
            List<Object[]> unidades = unidadeDAO.buscarUnidadesParaArvore(); 

            for (Object[] linha : unidades) {
                int idPais = (int) linha[0];
                String nomePais = (String) linha[1];
                int idEstado = (int) linha[2]; 
                String nomeEstado = (String) linha[3];
                
                if (idPais != idPaisAnterior) {
                    noPaisAtual = new DefaultMutableTreeNode(nomePais); 
                    raiz.add(noPaisAtual);
                    idPaisAnterior = idPais;
                }

                if (nomeEstado != null) {
                    AuxDAO estadoInfo = new AuxDAO(nomeEstado, idEstado);
                    noPaisAtual.add(new DefaultMutableTreeNode(estadoInfo));
                }
            }
            
            JtrUnidades.setModel(new DefaultTreeModel(raiz));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar a árvore: " + e.getMessage());
        }
    }

    private void carregarCbxEstados() {
        try {
            List<AuxDAO> estados = unidadeDAO.listarEstados(); 

            CbxEstado.removeAllItems();
            
            for (AuxDAO estado : estados) {
                CbxEstado.addItem(estado);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar estados =>>> " + e.getMessage());
        }
    }
    
    private void carregarCbxPais() {
        try {
            List<AuxDAO> paises = unidadeDAO.listarPaises(); 

            CbxPais.removeAllItems();
            
            for (AuxDAO pais : paises) {
                CbxPais.addItem(pais);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar lista de países: " + e.getMessage());
        }
    }

    private void carregarTabelaPaises() {
        String[] colunas = {"ID", "País"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0); 
        
        try {
            List<Object[]> paises = unidadeDAO.buscarPaisesNaTabela();
            
            for (Object[] linha : paises) {
                modelo.addRow(linha);
            }
            
            TblPaises.setModel(modelo);
            
            carregarCbxPais(); 
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao listar países: " + e.getMessage());
        }
    }
    
    private void salvarPais() {
        String nome = TxtNomePais.getText().trim();
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O nome do país é obrigatório.");
            return;
        }
        
        try {
            unidadeDAO.salvarPais(idPaisEmEdicao, nome);
            
            JOptionPane.showMessageDialog(this, "País salvo com sucesso!");
            
            carregarTabelaPaises();
            limparCamposPais();
            carregarUnidadesNaArvore(); 
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar país: " + e.getMessage());
        }
    }
    
    private void excluirPais() {
        int linha = TblPaises.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um país para excluir.");
            return;
        }

        int idPais = (Integer) TblPaises.getValueAt(linha, 0); 
        String nomePais = (String) TblPaises.getValueAt(linha, 1);

        int confirmar = JOptionPane.showConfirmDialog(this, 
            "Excluir país " + nomePais + " e tudo relacionado?", 
            "Confirmação", JOptionPane.YES_NO_OPTION);
        if (confirmar != JOptionPane.YES_OPTION) return;

        try {
            unidadeDAO.excluirPais(idPais);

            JOptionPane.showMessageDialog(this, "País excluído com sucesso.");
            carregarUnidadesNaArvore(); 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro: Não foi possível excluir o país. Certifique-se de que não há Estados vinculados. " + ex.getMessage());
        }
        atualizar();
    }
    
    private void carregarTabelaEstados() {
        String[] colunas = {"ID", "Estado", "ID País", "País"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0); 
        
        try {
            List<Object[]> estados = unidadeDAO.buscarEstadosNaTabela();
            
            for (Object[] linha : estados) {
                modelo.addRow(linha);
            }
            
            TblEstados.setModel(modelo);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao listar estados: " + e.getMessage());
        }
    }
    
    private void salvarEstado() {
        AuxDAO paisSelecionado = (AuxDAO) CbxPais.getSelectedItem();
        String nomeEstado = TxtNomeEstado.getText().trim();
        
        if (paisSelecionado == null || nomeEstado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione o País e digite o nome do Estado.");
            return;
        }
        
        int idPais = paisSelecionado.getId();
        boolean isUpdate = (idEstadoEmEdicao > 0);
        
        try {
            unidadeDAO.salvarEstado(idEstadoEmEdicao, nomeEstado, idPais);

            JOptionPane.showMessageDialog(this, "Estado salvo com sucesso!");
            
            carregarTabelaEstados();
            limparCamposEstado();
            carregarUnidadesNaArvore(); 
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar estado: " + e.getMessage());
        }
    }
    
    private void excluirEstado() {
        int linha = TblEstados.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um estado para excluir.");
            return;
        }

        int idEstado = (Integer) TblEstados.getValueAt(linha, 0); 
        String nomeEstado = (String) TblEstados.getValueAt(linha, 1);

        int confirmar = JOptionPane.showConfirmDialog(this, 
            "Excluir estado " + nomeEstado + " e todos os grupos relacionados?", 
            "Confirmação", JOptionPane.YES_NO_OPTION);
        if (confirmar != JOptionPane.YES_OPTION) return;

        try {
            unidadeDAO.excluirEstado(idEstado);

            JOptionPane.showMessageDialog(this, "Estado excluído com sucesso.");
            carregarUnidadesNaArvore(); 
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro: Não foi possível excluir o estado. Certifique-se de que não há Grupos Populacionais vinculados. " + ex.getMessage());
        }
        atualizar();
    }

    private void carregarCmbmpresas() {
        String sql = "SELECT id, nome FROM empresas ORDER BY nome";
        try (Connection conn = new Conexao().getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            CmbEmpresa.removeAllItems();
            while (rs.next()) {
                CmbEmpresa.addItem(new AuxDAO(rs.getString("nome"), rs.getInt("id")));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar lista de empresas: " + e.getMessage());
        }
    }

    private void carregarCmbNiveisAcesso() {
        CmbNivelAcesso.removeAllItems();
        CmbNivelAcesso.addItem("ADMIN");
        CmbNivelAcesso.addItem("GESTOR");
        CmbNivelAcesso.addItem("LEITURA");
    }

    private void salvarUsuario() {
        String usuario = TxtNomeUsuario.getText().trim();
        String email = TxtEmail.getText().trim();
        String senha = new String(PsfSenhaCadastro.getPassword()); 
        
        AuxDAO empresaSelecionada = (AuxDAO) CmbEmpresa.getSelectedItem();
        String nivelAcesso = (String) CmbNivelAcesso.getSelectedItem();
        
        if (usuario.isEmpty() || senha.isEmpty() || empresaSelecionada == null) {
            JOptionPane.showMessageDialog(this, "Usuário, senha e empresa são obrigatórios.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int idEmpresa = empresaSelecionada.getId();
        String senhaHash = senha; 

        String sql = "INSERT INTO usuarios (nome_usuario, senha_hash, email, id_empresa, nivel_acesso) VALUES (?, ?, ?, ?, ?)";

        try (Connection conn = new Conexao().getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, usuario);
            stmt.setString(2, senhaHash);
            stmt.setString(3, email);
            stmt.setInt(4, idEmpresa);
            stmt.setString(5, nivelAcesso);
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!");
            
            limparCamposUsuario();
            carregarTabelaUsuarios(); 

        } catch (SQLException e) {
            if (e.getMessage().contains("unique constraint")) {
                JOptionPane.showMessageDialog(this, "Erro: Nome de usuário ou Email já existe.", "Erro de Duplicidade", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar usuário: " + e.getMessage(), "Erro SQL", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void carregarTabelaUsuarios() {
        String[] colunas = {"ID", "Usuário", "Email", "Empresa", "Nível", "Ativo"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0); 
        
        String sql = "SELECT id, nome_usuario, email, nome_empresa, nivel_acesso, ativo FROM vw_usuarios_detalhe";

        try (Connection conn = new Conexao().getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {
            
            while (rs.next()) {
                Object[] linha = {
                    rs.getInt("id"),
                    rs.getString("nome_usuario"),
                    rs.getString("email"),
                    rs.getString("nome_empresa"),
                    rs.getString("nivel_acesso"),
                    rs.getBoolean("ativo") ? "Sim" : "Não" 
                };
                modelo.addRow(linha);
            }
            
            TblUsuarios.setModel(modelo);
            TblUsuarios.getColumnModel().getColumn(0).setMinWidth(0);
            TblUsuarios.getColumnModel().getColumn(0).setMaxWidth(0);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao listar usuários: " + e.getMessage(), "Erro SQL", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limparCampos() {
        idGrupoEmEdicao = 0;    
        TxtTamanho.setText("");
        TxtTipo.setText("");
        TxtNacionalidade.setText("");
        TxtReligiao.setText("");
        BtnSalvar.setText("CADASTRAR");
    }

    private void limparCamposPais() {
        TxtNomePais.setText("");
    }

    private void limparCamposEstado() {
        TxtNomeEstado.setText("");
    }
    
    private void limparCamposUsuario() {
        TxtNomeUsuario.setText("");
        PsfSenhaCadastro.setText("");
        TxtEmail.setText("");
        CmbEmpresa.setSelectedIndex(0); 
        CmbNivelAcesso.setSelectedIndex(0);
    }
    
    private void adicionarListenerNaArvore() {
        JtrUnidades.addTreeSelectionListener(new TreeSelectionListener() {
            @Override
            public void valueChanged(TreeSelectionEvent e) {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) 
                                             JtrUnidades.getLastSelectedPathComponent();

                if (node == null) return;

                Object userObject = node.getUserObject();

                if (userObject instanceof AuxDAO) {
                    AuxDAO estadoSelecionado = (AuxDAO) userObject;
                    int idEstado = estadoSelecionado.getId();

                    carregarTabelaGrupos(idEstado);
                } 
            }
        });
    }
    
    private void adicionarListenerTabelaEdicao() {
        TblGruposEdicao.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && TblGruposEdicao.getSelectedRow() != -1) {
                
                int linha = TblGruposEdicao.getSelectedRow();
                DefaultTableModel modelo = (DefaultTableModel) TblGruposEdicao.getModel();
                
                idGrupoEmEdicao = (int) modelo.getValueAt(linha, 0); 
                
                String nomeEstado = (String) modelo.getValueAt(linha, 5); 
                
                TxtTamanho.setText(modelo.getValueAt(linha, 1).toString());
                TxtTipo.setText((String) modelo.getValueAt(linha, 2));
                TxtNacionalidade.setText((String) modelo.getValueAt(linha, 3));
                TxtReligiao.setText((String) modelo.getValueAt(linha, 4));
                
                for (int i = 0; i < CbxEstado.getItemCount(); i++) {
                    if (CbxEstado.getItemAt(i).toString().equals(nomeEstado)) {
                        CbxEstado.setSelectedIndex(i);
                        break;
                    }
                }
                BtnSalvar.setText("EDITAR"); 
            }
        });
    }

    private void adicionarListenerTabelaPaises() {
        TblPaises.getSelectionModel().addListSelectionListener(e -> {
            
            if (!e.getValueIsAdjusting() && TblPaises.getSelectedRow() != -1) {
                
                int linha = TblPaises.getSelectedRow();
                DefaultTableModel modelo = (DefaultTableModel) TblPaises.getModel();
                
                if (linha >= 0 && linha < modelo.getRowCount()) {

                    Object idObj = modelo.getValueAt(linha, 0); 
                    Object nomeObj = modelo.getValueAt(linha, 1); 

                    if (idObj == null) {
                        System.out.println("Linha selecionada com ID nulo. Resetando formulário.");
                        limparCamposPais(); 
                        return; 
                    }
                    
                    idPaisEmEdicao = (int) idObj;
                    
                    String nomePais = (nomeObj != null) ? nomeObj.toString() : "";
                    TxtNomePais.setText(nomePais);
                    
                    System.out.println("Dados carregados com sucesso: ID " + idPaisEmEdicao);
                    
                    BtnSalvarPais.setText("EDITAR");
                    
                } else {
                    limparCamposPais();
                }
            }
        });
    }


    private void adicionarListenerTabelaEstados() {
        TblEstados.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && TblEstados.getSelectedRow() != -1) {
                int linha = TblEstados.getSelectedRow();
                DefaultTableModel modelo = (DefaultTableModel) TblEstados.getModel();
                
                idEstadoEmEdicao = (int) modelo.getValueAt(linha, 0); 
                TxtNomeEstado.setText((String) modelo.getValueAt(linha, 1)); 
                
                String nomePais = (String) modelo.getValueAt(linha, 3); 
                
                for (int i = 0; i < CbxPais.getItemCount(); i++) {
                    if (CbxPais.getItemAt(i).toString().equals(nomePais)) {
                        CbxPais.setSelectedIndex(i);
                        break;
                    }
                }
                BtnSalvarEstado.setText("EDITAR");
            }
        });
    }
    
    private void adicionarListenerTabelaUsuarios() {
        TblUsuarios.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && TblUsuarios.getSelectedRow() != -1) {
                
                int linha = TblUsuarios.getSelectedRow();
                DefaultTableModel modelo = (DefaultTableModel) TblUsuarios.getModel();
                
                Object idObj = modelo.getValueAt(linha, 0);
                
                if (idObj == null) {
                    limparCamposUsuario();
                    return;
                }
                
                idUsuarioEmEdicao = (int) idObj;
                
                TxtNomeUsuario.setText(modelo.getValueAt(linha, 1).toString());
                TxtEmail.setText(modelo.getValueAt(linha, 2).toString());      
                
                String nivel = modelo.getValueAt(linha, 4).toString();
                CmbNivelAcesso.setSelectedItem(nivel);
                
                String nomeEmpresa = modelo.getValueAt(linha, 3).toString();
                for (int i = 0; i < CmbEmpresa.getItemCount(); i++) {
                    if (CmbEmpresa.getItemAt(i).toString().equals(nomeEmpresa)) {
                        CmbEmpresa.setSelectedIndex(i);
                        break;
                    }
                }
                
                PsfSenhaCadastro.setText(""); 
                
                BtnSalvarUsuario.setText("Editar"); 
            }
        });
    }

    private void configurarPermissoes() {
        String nivel = Sessao.getNivelAcesso();
        System.out.println("Configurando permissões para o nível: " + nivel);

        boolean podeEscrever = "ADMIN".equals(nivel) || "GESTOR".equals(nivel); 
        boolean isAdmin = "ADMIN".equals(nivel);
        
        //JONATHAN: PARA INGONOBIOS TIPO VC Q N SAVE O MINIMO DE INGLES ISADMIN = É ADMIN

        BtnSalvar.setEnabled(podeEscrever);
        BtnExcluir.setEnabled(podeEscrever);
        TxtTamanho.setEditable(podeEscrever);
        TxtTipo.setEditable(podeEscrever);
        TxtNacionalidade.setEditable(podeEscrever);
        TxtReligiao.setEditable(podeEscrever);
        CbxEstado.setEnabled(podeEscrever); 

        BtnSalvarPais.setEnabled(isAdmin);
        BtnExcluirPais.setEnabled(isAdmin);
        TxtNomePais.setEditable(isAdmin);
        BtnSalvarEstado.setEnabled(isAdmin);
        BtnExcluirEstado.setEnabled(isAdmin);
        TxtNomeEstado.setEditable(isAdmin);
        CbxPais.setEnabled(isAdmin);
        


        int indiceDaAbaUsuarios = 3; 

        if (jTabbedPane1.getTabCount() > indiceDaAbaUsuarios) {
            jTabbedPane1.setEnabledAt(indiceDaAbaUsuarios, isAdmin);
        }
        
        BtnSalvarUsuario.setEnabled(isAdmin);
        TxtNomeUsuario.setEditable(isAdmin);
        PsfSenhaCadastro.setEditable(isAdmin);
        TxtEmail.setEditable(isAdmin);
        CmbEmpresa.setEnabled(isAdmin);
        CmbNivelAcesso.setEnabled(isAdmin);
    }
    
    private void atualizar(){
        carregarUnidadesNaArvore();
            
        carregarCbxEstados(); 
        carregarTabelaEdicao(); 
            
        carregarCbxPais();
        carregarTabelaPaises();    
        carregarTabelaEstados();
        adicionarListenerTabelaPaises();
        adicionarListenerTabelaEstados();
        carregarCmbmpresas();
        carregarCmbNiveisAcesso();
        carregarTabelaUsuarios();
            
    }
    
    private void gerarRelatorio(String tipo) {
    try {
        String caminho = "src/main/resources/relatorios/" + tipo + ".jasper";
        
        Connection con = Conexao.getConnection(); 
        Map<String, Object> parametros = new HashMap<>(); 
        
        RelatorioUtil.abrirPDF(caminho, parametros, con);
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
}
}